/**
 * База данных продуктов (200+ позиций)
 * Источники: MyFitnessPal, FatSecret, USDA, Российские продукты
 */

export const foodDatabase = [
  // === ЗАВТРАК ===
  { id: 1, name: 'Овсянка на воде', category: 'breakfast', portion: '100г', calories: 68, protein: 2.4, fat: 1.4, carbs: 12 },
  { id: 2, name: 'Овсянка на молоке', category: 'breakfast', portion: '100г', calories: 102, protein: 3.5, fat: 2.5, carbs: 17 },
  { id: 3, name: 'Геркулес', category: 'breakfast', portion: '100г', calories: 68, protein: 2.4, fat: 1.4, carbs: 12 },
  { id: 4, name: 'Яйцо куриное (1 шт)', category: 'breakfast', portion: '50г', calories: 78, protein: 6, fat: 5, carbs: 0.6 },
  { id: 5, name: 'Яйца (2 шт)', category: 'breakfast', portion: '100г', calories: 155, protein: 13, fat: 11, carbs: 1.1 },
  { id: 6, name: 'Яичница', category: 'breakfast', portion: '100г', calories: 214, protein: 14, fat: 16, carbs: 1.5 },
  { id: 7, name: 'Омлет (2 яйца)', category: 'breakfast', portion: '150г', calories: 250, protein: 18, fat: 18, carbs: 4 },
  { id: 8, name: 'Омлет с сыром', category: 'breakfast', portion: '150г', calories: 320, protein: 20, fat: 24, carbs: 5 },
  { id: 9, name: 'Творог 5%', category: 'breakfast', portion: '100г', calories: 121, protein: 17, fat: 5, carbs: 3.4 },
  { id: 10, name: 'Творог 2%', category: 'breakfast', portion: '100г', calories: 103, protein: 18, fat: 2, carbs: 3.4 },
  { id: 11, name: 'Творог обезжиренный', category: 'breakfast', portion: '100г', calories: 75, protein: 16, fat: 0.3, carbs: 2.4 },
  { id: 12, name: 'Творог зернистый', category: 'breakfast', portion: '100г', calories: 110, protein: 18, fat: 3, carbs: 4 },
  { id: 13, name: 'Сырники', category: 'breakfast', portion: '100г', calories: 220, protein: 14, fat: 12, carbs: 15 },
  { id: 14, name: 'Сырники из духовки', category: 'breakfast', portion: '100г', calories: 180, protein: 15, fat: 8, carbs: 14 },
  { id: 15, name: 'Гречневая каша', category: 'breakfast', portion: '100г', calories: 110, protein: 4, fat: 1, carbs: 21 },
  { id: 16, name: 'Гречка с молоком', category: 'breakfast', portion: '100г', calories: 140, protein: 5, fat: 2.5, carbs: 25 },
  { id: 17, name: 'Рисовая каша', category: 'breakfast', portion: '100г', calories: 130, protein: 2.7, fat: 0.3, carbs: 28 },
  { id: 18, name: 'Манная каша', category: 'breakfast', portion: '100г', calories: 100, protein: 3, fat: 1, carbs: 20 },
  { id: 19, name: 'Пшенная каша', category: 'breakfast', portion: '100г', calories: 100, protein: 3, fat: 1, carbs: 20 },
  { id: 20, name: 'Кукурузная каша', category: 'breakfast', portion: '100г', calories: 90, protein: 2.5, fat: 0.8, carbs: 18 },
  { id: 21, name: 'Банан', category: 'breakfast', portion: '1 шт (120г)', calories: 105, protein: 1.3, fat: 0.4, carbs: 27 },
  { id: 22, name: 'Яблоко', category: 'breakfast', portion: '1 шт (180г)', calories: 95, protein: 0.5, fat: 0.3, carbs: 25 },
  { id: 23, name: 'Яблоко зеленое', category: 'breakfast', portion: '1 шт (150г)', calories: 70, protein: 0.3, fat: 0.2, carbs: 18 },
  { id: 24, name: 'Груша', category: 'breakfast', portion: '1 шт (180г)', calories: 100, protein: 0.5, fat: 0.2, carbs: 26 },
  { id: 25, name: 'Апельсин', category: 'breakfast', portion: '1 шт (150г)', calories: 60, protein: 1.2, fat: 0.2, carbs: 15 },
  { id: 26, name: 'Мандарин', category: 'breakfast', portion: '1 шт (80г)', calories: 40, protein: 0.5, fat: 0.1, carbs: 10 },
  { id: 27, name: 'Виноград', category: 'breakfast', portion: '100г', calories: 70, protein: 0.7, fat: 0.2, carbs: 17 },
  { id: 28, name: 'Клубника', category: 'breakfast', portion: '100г', calories: 32, protein: 0.7, fat: 0.3, carbs: 7.5 },
  { id: 29, name: 'Черника', category: 'breakfast', portion: '100г', calories: 44, protein: 0.7, fat: 0.3, carbs: 11 },
  { id: 30, name: 'Малина', category: 'breakfast', portion: '100г', calories: 52, protein: 1.2, fat: 0.7, carbs: 12 },
  { id: 31, name: 'Смородина', category: 'breakfast', portion: '100г', calories: 43, protein: 1, fat: 0.4, carbs: 10 },
  { id: 32, name: 'Молоко 2.5%', category: 'breakfast', portion: '200мл', calories: 100, protein: 6, fat: 5, carbs: 8 },
  { id: 33, name: 'Молоко 1%', category: 'breakfast', portion: '200мл', calories: 74, protein: 6, fat: 2, carbs: 8 },
  { id: 34, name: 'Молоко обезжиренное', category: 'breakfast', portion: '200мл', calories: 60, protein: 6, fat: 0.5, carbs: 8 },
  { id: 35, name: 'Кефир 2.5%', category: 'breakfast', portion: '200мл', calories: 100, protein: 6, fat: 5, carbs: 8 },
  { id: 36, name: 'Кефир 1%', category: 'breakfast', portion: '200мл', calories: 74, protein: 6, fat: 2, carbs: 8 },
  { id: 37, name: 'Йогурт натуральный', category: 'breakfast', portion: '150г', calories: 100, protein: 5, fat: 3, carbs: 12 },
  { id: 38, name: 'Йогурт греческий', category: 'breakfast', portion: '150г', calories: 100, protein: 15, fat: 0, carbs: 6 },
  { id: 39, name: 'Йогурт с фруктами', category: 'breakfast', portion: '150г', calories: 140, protein: 4, fat: 2, carbs: 26 },
  { id: 40, name: 'Творожный сырок', category: 'breakfast', portion: '1 шт (50г)', calories: 160, protein: 8, fat: 10, carbs: 10 },
  { id: 41, name: 'Снежок', category: 'breakfast', portion: '100г', calories: 120, protein: 6, fat: 4, carbs: 16 },
  { id: 42, name: 'Смузи протеиновый', category: 'breakfast', portion: '300мл', calories: 180, protein: 25, fat: 3, carbs: 15 },
  { id: 43, name: 'Смузи фруктовый', category: 'breakfast', portion: '300мл', calories: 150, protein: 3, fat: 1, carbs: 35 },
  { id: 44, name: 'Какао с молоком', category: 'breakfast', portion: '250мл', calories: 180, protein: 7, fat: 6, carbs: 24 },
  { id: 45, name: 'Кофе с молоком', category: 'breakfast', portion: '250мл', calories: 60, protein: 3, fat: 2, carbs: 7 },
  { id: 46, name: 'Латте', category: 'breakfast', portion: '300мл', calories: 150, protein: 6, fat: 6, carbs: 16 },
  { id: 47, name: 'Хлопья кукурузные', category: 'breakfast', portion: '30г', calories: 110, protein: 2, fat: 0.5, carbs: 24 },
  { id: 48, name: 'Мюсли', category: 'breakfast', portion: '50г', calories: 200, protein: 4, fat: 4, carbs: 36 },
  { id: 49, name: 'Гранола', category: 'breakfast', portion: '50г', calories: 220, protein: 5, fat: 8, carbs: 35 },
  { id: 50, name: 'Панкейки', category: 'breakfast', portion: '100г', calories: 227, protein: 6, fat: 8, carbs: 35 },
  
  // === ОБЕД ===
  { id: 51, name: 'Куриная грудка', category: 'lunch', portion: '100г', calories: 165, protein: 31, fat: 3.6, carbs: 0 },
  { id: 52, name: 'Куриная грудка отварная', category: 'lunch', portion: '100г', calories: 130, protein: 30, fat: 1, carbs: 0 },
  { id: 53, name: 'Куриное филе', category: 'lunch', portion: '100г', calories: 110, protein: 23, fat: 1.5, carbs: 0 },
  { id: 54, name: 'Курица запеченная', category: 'lunch', portion: '100г', calories: 180, protein: 25, fat: 8, carbs: 0 },
  { id: 55, name: 'Курица гриль', category: 'lunch', portion: '100г', calories: 190, protein: 25, fat: 10, carbs: 0 },
  { id: 56, name: 'Куриные бедра', category: 'lunch', portion: '100г', calories: 210, protein: 24, fat: 12, carbs: 0 },
  { id: 57, name: 'Куриные крылышки', category: 'lunch', portion: '100г', calories: 230, protein: 23, fat: 14, carbs: 0 },
  { id: 58, name: 'Индейка', category: 'lunch', portion: '100г', calories: 135, protein: 30, fat: 1, carbs: 0 },
  { id: 59, name: 'Индейка отварная', category: 'lunch', portion: '100г', calories: 115, protein: 28, fat: 0.5, carbs: 0 },
  { id: 60, name: 'Говядина', category: 'lunch', portion: '100г', calories: 250, protein: 26, fat: 15, carbs: 0 },
  { id: 61, name: 'Говядина отварная', category: 'lunch', portion: '100г', calories: 180, protein: 28, fat: 6, carbs: 0 },
  { id: 62, name: 'Говядина запеченная', category: 'lunch', portion: '100г', calories: 220, protein: 26, fat: 12, carbs: 0 },
  { id: 63, name: 'Стейк говяжий', category: 'lunch', portion: '100г', calories: 280, protein: 25, fat: 20, carbs: 0 },
  { id: 64, name: 'Фарш говяжий', category: 'lunch', portion: '100г', calories: 250, protein: 26, fat: 15, carbs: 0 },
  { id: 65, name: 'Свинина', category: 'lunch', portion: '100г', calories: 320, protein: 25, fat: 23, carbs: 0 },
  { id: 66, name: 'Свинина отварная', category: 'lunch', portion: '100г', calories: 240, protein: 28, fat: 13, carbs: 0 },
  { id: 67, name: 'Шашлык свиной', category: 'lunch', portion: '100г', calories: 280, protein: 22, fat: 20, carbs: 0 },
  { id: 68, name: 'Бекон', category: 'lunch', portion: '30г', calories: 150, protein: 10, fat: 12, carbs: 0 },
  { id: 69, name: 'Рыба (лосось)', category: 'lunch', portion: '100г', calories: 208, protein: 20, fat: 13, carbs: 0 },
  { id: 70, name: 'Лосось запеченный', category: 'lunch', portion: '100г', calories: 220, protein: 22, fat: 14, carbs: 0 },
  { id: 71, name: 'Форель', category: 'lunch', portion: '100г', calories: 140, protein: 20, fat: 6, carbs: 0 },
  { id: 72, name: 'Тунец', category: 'lunch', portion: '100г', calories: 130, protein: 29, fat: 1, carbs: 0 },
  { id: 73, name: 'Тунец консервированный', category: 'lunch', portion: '100г', calories: 116, protein: 26, fat: 1, carbs: 0 },
  { id: 74, name: 'Семга', category: 'lunch', portion: '100г', calories: 200, protein: 20, fat: 13, carbs: 0 },
  { id: 75, name: 'Сом', category: 'lunch', portion: '100г', calories: 95, protein: 18, fat: 2, carbs: 0 },
  { id: 76, name: 'Треска', category: 'lunch', portion: '100г', calories: 82, protein: 18, fat: 0.7, carbs: 0 },
  { id: 77, name: 'Минтай', category: 'lunch', portion: '100г', calories: 72, protein: 16, fat: 0.5, carbs: 0 },
  { id: 78, name: 'Камбала', category: 'lunch', portion: '100г', calories: 90, protein: 19, fat: 1, carbs: 0 },
  { id: 79, name: 'Горбуша', category: 'lunch', portion: '100г', calories: 140, protein: 22, fat: 5, carbs: 0 },
  { id: 80, name: 'Сельдь', category: 'lunch', portion: '100г', calories: 240, protein: 18, fat: 18, carbs: 0 },
  { id: 81, name: 'Сардины', category: 'lunch', portion: '100г', calories: 200, protein: 25, fat: 11, carbs: 0 },
  { id: 82, name: 'Рис белый', category: 'lunch', portion: '100г', calories: 130, protein: 2.7, fat: 0.3, carbs: 28 },
  { id: 83, name: 'Рис бурый', category: 'lunch', portion: '100г', calories: 111, protein: 2.6, fat: 0.9, carbs: 23 },
  { id: 84, name: 'Рис отварной', category: 'lunch', portion: '100г', calories: 130, protein: 2.7, fat: 0.3, carbs: 28 },
  { id: 85, name: 'Гречка', category: 'lunch', portion: '100г', calories: 110, protein: 4, fat: 1, carbs: 21 },
  { id: 86, name: 'Макароны', category: 'lunch', portion: '100г', calories: 131, protein: 5, fat: 1, carbs: 25 },
  { id: 87, name: 'Макароны отварные', category: 'lunch', portion: '100г', calories: 100, protein: 3.5, fat: 0.5, carbs: 20 },
  { id: 88, name: 'Спагетти', category: 'lunch', portion: '100г', calories: 131, protein: 5, fat: 1, carbs: 25 },
  { id: 89, name: 'Картофель отварной', category: 'lunch', portion: '100г', calories: 82, protein: 2, fat: 0.1, carbs: 17 },
  { id: 90, name: 'Картофель запеченный', category: 'lunch', portion: '100г', calories: 93, protein: 2.5, fat: 0.4, carbs: 20 },
  { id: 91, name: 'Пюре картофельное', category: 'lunch', portion: '100г', calories: 90, protein: 2, fat: 3, carbs: 14 },
  { id: 92, name: 'Картофель жареный', category: 'lunch', portion: '100г', calories: 150, protein: 2, fat: 7, carbs: 18 },
  { id: 93, name: 'Овощи на пару', category: 'lunch', portion: '150г', calories: 75, protein: 3, fat: 0.5, carbs: 15 },
  { id: 94, name: 'Брокколи', category: 'lunch', portion: '100г', calories: 34, protein: 2.8, fat: 0.4, carbs: 7 },
  { id: 95, name: 'Брокколи отварная', category: 'lunch', portion: '100г', calories: 35, protein: 2.4, fat: 0.4, carbs: 7 },
  { id: 96, name: 'Цветная капуста', category: 'lunch', portion: '100г', calories: 25, protein: 1.9, fat: 0.3, carbs: 5 },
  { id: 97, name: 'Морковь', category: 'lunch', portion: '100г', calories: 41, protein: 0.9, fat: 0.2, carbs: 10 },
  { id: 98, name: 'Морковь отварная', category: 'lunch', portion: '100г', calories: 35, protein: 0.8, fat: 0.2, carbs: 8 },
  { id: 99, name: 'Свекла', category: 'lunch', portion: '100г', calories: 43, protein: 1.6, fat: 0.2, carbs: 10 },
  { id: 100, name: 'Лук репчатый', category: 'lunch', portion: '100г', calories: 40, protein: 1.1, fat: 0.1, carbs: 9 },
  { id: 101, name: 'Помидор', category: 'lunch', portion: '1 шт (150г)', calories: 27, protein: 1.3, fat: 0.3, carbs: 6 },
  { id: 102, name: 'Огурец', category: 'lunch', portion: '1 шт (100г)', calories: 15, protein: 0.7, fat: 0.1, carbs: 3.6 },
  { id: 103, name: 'Перец болгарский', category: 'lunch', portion: '1 шт (120г)', calories: 31, protein: 1, fat: 0.3, carbs: 6 },
  { id: 104, name: 'Кабачок', category: 'lunch', portion: '100г', calories: 17, protein: 0.6, fat: 0.3, carbs: 3.5 },
  { id: 105, name: 'Баклажан', category: 'lunch', portion: '100г', calories: 25, protein: 1, fat: 0.2, carbs: 6 },
  { id: 106, name: 'Салат Цезарь', category: 'lunch', portion: '200г', calories: 320, protein: 15, fat: 22, carbs: 18 },
  { id: 107, name: 'Салат Оливье', category: 'lunch', portion: '200г', calories: 300, protein: 8, fat: 20, carbs: 22 },
  { id: 108, name: 'Винегрет', category: 'lunch', portion: '200г', calories: 180, protein: 3, fat: 8, carbs: 24 },
  { id: 109, name: 'Греческий салат', category: 'lunch', portion: '200г', calories: 180, protein: 5, fat: 14, carbs: 10 },
  { id: 110, name: 'Суп куриный', category: 'lunch', portion: '250мл', calories: 150, protein: 12, fat: 6, carbs: 10 },
  { id: 111, name: 'Суп овощной', category: 'lunch', portion: '250мл', calories: 80, protein: 3, fat: 2, carbs: 12 },
  { id: 112, name: 'Суп грибной', category: 'lunch', portion: '250мл', calories: 100, protein: 4, fat: 5, carbs: 10 },
  { id: 113, name: 'Борщ', category: 'lunch', portion: '250мл', calories: 180, protein: 6, fat: 8, carbs: 20 },
  { id: 114, name: 'Щи', category: 'lunch', portion: '250мл', calories: 100, protein: 4, fat: 4, carbs: 12 },
  { id: 115, name: 'Рассольник', category: 'lunch', portion: '250мл', calories: 150, protein: 5, fat: 6, carbs: 18 },
  
  // === УЖИН ===
  { id: 116, name: 'Рыба на пару', category: 'dinner', portion: '100г', calories: 100, protein: 22, fat: 1, carbs: 0 },
  { id: 117, name: 'Рыба запеченная', category: 'dinner', portion: '100г', calories: 150, protein: 20, fat: 7, carbs: 0 },
  { id: 118, name: 'Куриная грудка вечер', category: 'dinner', portion: '100г', calories: 130, protein: 30, fat: 1, carbs: 0 },
  { id: 119, name: 'Творог обезжиренный вечер', category: 'dinner', portion: '100г', calories: 75, protein: 16, fat: 0.3, carbs: 2.4 },
  { id: 120, name: 'Кефир 1% вечер', category: 'dinner', portion: '200мл', calories: 74, protein: 6, fat: 2, carbs: 8 },
  { id: 121, name: 'Йогурт греческий вечер', category: 'dinner', portion: '150г', calories: 100, protein: 15, fat: 0, carbs: 6 },
  { id: 122, name: 'Салат овощной', category: 'dinner', portion: '150г', calories: 45, protein: 2, fat: 0.3, carbs: 9 },
  { id: 123, name: 'Салат из огурцов', category: 'dinner', portion: '150г', calories: 25, protein: 1, fat: 0.2, carbs: 5 },
  { id: 124, name: 'Салат из помидоров', category: 'dinner', portion: '150г', calories: 35, protein: 1.5, fat: 0.3, carbs: 7 },
  { id: 125, name: 'Омлет с овощами', category: 'dinner', portion: '200г', calories: 200, protein: 14, fat: 12, carbs: 8 },
  { id: 126, name: 'Овощное рагу', category: 'dinner', portion: '200г', calories: 120, protein: 4, fat: 5, carbs: 15 },
  { id: 127, name: 'Рагу овощное', category: 'dinner', portion: '200г', calories: 100, protein: 3, fat: 4, carbs: 14 },
  { id: 128, name: 'Тушеные овощи', category: 'dinner', portion: '200г', calories: 90, protein: 3, fat: 3, carbs: 13 },
  { id: 129, name: 'Запеченные овощи', category: 'dinner', portion: '200г', calories: 100, protein: 3, fat: 4, carbs: 12 },
  { id: 130, name: 'Творог с зеленью', category: 'dinner', portion: '100г', calories: 120, protein: 14, fat: 5, carbs: 3 },
  { id: 131, name: 'Яичница с овощами', category: 'dinner', portion: '150г', calories: 200, protein: 12, fat: 14, carbs: 5 },
  { id: 132, name: 'Филе индейки', category: 'dinner', portion: '100г', calories: 120, protein: 28, fat: 1, carbs: 0 },
  { id: 133, name: 'Рыба с овощами', category: 'dinner', portion: '150г', calories: 180, protein: 25, fat: 6, carbs: 8 },
  { id: 134, name: 'Курица с овощами', category: 'dinner', portion: '150г', calories: 200, protein: 28, fat: 5, carbs: 10 },
  
  // === ПЕРЕКУСЫ ===
  { id: 135, name: 'Орехи грецкие', category: 'snack', portion: '30г', calories: 200, protein: 5, fat: 20, carbs: 4 },
  { id: 136, name: 'Орехи миндаль', category: 'snack', portion: '30г', calories: 170, protein: 6, fat: 15, carbs: 6 },
  { id: 137, name: 'Орехи кешью', category: 'snack', portion: '30г', calories: 165, protein: 5, fat: 13, carbs: 9 },
  { id: 138, name: 'Орехи фисташки', category: 'snack', portion: '30г', calories: 160, protein: 6, fat: 13, carbs: 8 },
  { id: 139, name: 'Орехи арахис', category: 'snack', portion: '30г', calories: 170, protein: 7, fat: 14, carbs: 5 },
  { id: 140, name: 'Семечки подсолнуха', category: 'snack', portion: '30г', calories: 175, protein: 6, fat: 15, carbs: 6 },
  { id: 141, name: 'Семечки тыквенные', category: 'snack', portion: '30г', calories: 170, protein: 9, fat: 14, carbs: 4 },
  { id: 142, name: 'Протеиновый батончик', category: 'snack', portion: '1 шт', calories: 200, protein: 20, fat: 7, carbs: 22 },
  { id: 143, name: 'Энергетический батончик', category: 'snack', portion: '1 шт', calories: 250, protein: 5, fat: 10, carbs: 40 },
  { id: 144, name: 'Фруктовый салат', category: 'snack', portion: '150г', calories: 80, protein: 1, fat: 0.2, carbs: 20 },
  { id: 145, name: 'Фруктовый микс', category: 'snack', portion: '100г', calories: 70, protein: 1, fat: 0.3, carbs: 17 },
  { id: 146, name: 'Хлебцы', category: 'snack', portion: '2 шт', calories: 60, protein: 2, fat: 0.5, carbs: 12 },
  { id: 147, name: 'Хлебцы рисовые', category: 'snack', portion: '2 шт', calories: 50, protein: 1, fat: 0.2, carbs: 11 },
  { id: 148, name: 'Рисовые хлебцы', category: 'snack', portion: '2 шт', calories: 50, protein: 1, fat: 0.2, carbs: 11 },
  { id: 149, name: 'Тёмный шоколад 70%', category: 'snack', portion: '30г', calories: 180, protein: 2, fat: 12, carbs: 15 },
  { id: 150, name: 'Шоколад молочный', category: 'snack', portion: '30г', calories: 160, protein: 2, fat: 9, carbs: 18 },
  { id: 151, name: 'Шоколад белый', category: 'snack', portion: '30г', calories: 170, protein: 2, fat: 10, carbs: 17 },
  { id: 152, name: 'Конфета шоколадная', category: 'snack', portion: '1 шт', calories: 60, protein: 0.5, fat: 3, carbs: 8 },
  { id: 153, name: 'Мармелад', category: 'snack', portion: '30г', calories: 100, protein: 0, fat: 0, carbs: 25 },
  { id: 154, name: 'Зефир', category: 'snack', portion: '1 шт (40г)', calories: 120, protein: 0.5, fat: 0, carbs: 29 },
  { id: 155, name: 'Пастила', category: 'snack', portion: '30г', calories: 100, protein: 0.5, fat: 0, carbs: 24 },
  { id: 156, name: 'Печенье овсяное', category: 'snack', portion: '2 шт (30г)', calories: 130, protein: 2, fat: 4, carbs: 22 },
  { id: 157, name: 'Печенье крекер', category: 'snack', portion: '3 шт (30г)', calories: 130, protein: 2, fat: 5, carbs: 18 },
  { id: 158, name: 'Печенье сахарное', category: 'snack', portion: '2 шт (30г)', calories: 140, protein: 1.5, fat: 5, carbs: 22 },
  { id: 159, name: 'Вафли', category: 'snack', portion: '1 шт (30г)', calories: 130, protein: 1.5, fat: 5, carbs: 20 },
  { id: 160, name: 'Пряники', category: 'snack', portion: '1 шт (40г)', calories: 140, protein: 1.5, fat: 2, carbs: 28 },
  { id: 161, name: 'Арахисовая паста', category: 'snack', portion: '30г', calories: 190, protein: 7, fat: 16, carbs: 6 },
  { id: 162, name: 'Мёд', category: 'snack', portion: '1 ст.л.', calories: 60, protein: 0.1, fat: 0, carbs: 15 },
  { id: 163, name: 'Варенье', category: 'snack', portion: '1 ст.л.', calories: 50, protein: 0.1, fat: 0, carbs: 13 },
  { id: 164, name: 'Сухофрукты (смесь)', category: 'snack', portion: '30г', calories: 90, protein: 1, fat: 0.2, carbs: 22 },
  { id: 165, name: 'Курага', category: 'snack', portion: '30г', calories: 80, protein: 1, fat: 0.1, carbs: 20 },
  { id: 166, name: 'Изюм', category: 'snack', portion: '30г', calories: 90, protein: 0.8, fat: 0.1, carbs: 23 },
  { id: 167, name: 'Чернослив', category: 'snack', portion: '30г', calories: 80, protein: 1, fat: 0.2, carbs: 20 },
  { id: 168, name: 'Инжир сушеный', category: 'snack', portion: '30г', calories: 85, protein: 1.2, fat: 0.3, carbs: 21 },
  { id: 169, name: 'Финики', category: 'snack', portion: '30г', calories: 90, protein: 0.6, fat: 0.1, carbs: 23 },
  { id: 170, name: 'Попкорн', category: 'snack', portion: '30г', calories: 110, protein: 3, fat: 1, carbs: 20 },
  { id: 171, name: 'Чипсы', category: 'snack', portion: '30г', calories: 160, protein: 2, fat: 10, carbs: 15 },
  { id: 172, name: 'Снеки', category: 'snack', portion: '30г', calories: 150, protein: 2, fat: 8, carbs: 18 },
  
  // === НАПИТКИ ===
  { id: 173, name: 'Кофе чёрный', category: 'drink', portion: '200мл', calories: 2, protein: 0.3, fat: 0, carbs: 0 },
  { id: 174, name: 'Эспрессо', category: 'drink', portion: '30мл', calories: 3, protein: 0.1, fat: 0, carbs: 0.5 },
  { id: 175, name: 'Американо', category: 'drink', portion: '150мл', calories: 5, protein: 0.3, fat: 0, carbs: 1 },
  { id: 176, name: 'Капучино', category: 'drink', portion: '200мл', calories: 80, protein: 4, fat: 4, carbs: 6 },
  { id: 177, name: 'Латте', category: 'drink', portion: '300мл', calories: 150, protein: 6, fat: 6, carbs: 16 },
  { id: 178, name: 'Раф', category: 'drink', portion: '200мл', calories: 180, protein: 4, fat: 10, carbs: 16 },
  { id: 179, name: 'Зелёный чай', category: 'drink', portion: '200мл', calories: 0, protein: 0, fat: 0, carbs: 0 },
  { id: 180, name: 'Чёрный чай', category: 'drink', portion: '200мл', calories: 2, protein: 0, fat: 0, carbs: 0.5 },
  { id: 181, name: 'Чай с сахаром', category: 'drink', portion: '200мл', calories: 40, protein: 0, fat: 0, carbs: 10 },
  { id: 182, name: 'Чай с мёдом', category: 'drink', portion: '200мл', calories: 60, protein: 0.1, fat: 0, carbs: 15 },
  { id: 183, name: 'Травяной чай', category: 'drink', portion: '200мл', calories: 0, protein: 0, fat: 0, carbs: 0 },
  { id: 184, name: 'Ромашковый чай', category: 'drink', portion: '200мл', calories: 0, protein: 0, fat: 0, carbs: 0 },
  { id: 185, name: 'Имбирный чай', category: 'drink', portion: '200мл', calories: 10, protein: 0, fat: 0, carbs: 2 },
  { id: 186, name: 'Сок апельсиновый', category: 'drink', portion: '200мл', calories: 90, protein: 1.5, fat: 0.5, carbs: 21 },
  { id: 187, name: 'Сок яблочный', category: 'drink', portion: '200мл', calories: 90, protein: 0.3, fat: 0.2, carbs: 22 },
  { id: 188, name: 'Сок томатный', category: 'drink', portion: '200мл', calories: 40, protein: 1.5, fat: 0.2, carbs: 9 },
  { id: 189, name: 'Сок виноградный', category: 'drink', portion: '200мл', calories: 130, protein: 0.5, fat: 0.2, carbs: 32 },
  { id: 190, name: 'Сок морковный', category: 'drink', portion: '200мл', calories: 80, protein: 1.5, fat: 0.4, carbs: 18 },
  { id: 191, name: 'Компот фруктовый', category: 'drink', portion: '200мл', calories: 60, protein: 0.3, fat: 0.1, carbs: 15 },
  { id: 192, name: 'Морс', category: 'drink', portion: '200мл', calories: 50, protein: 0.1, fat: 0, carbs: 13 },
  { id: 193, name: 'Кисель', category: 'drink', portion: '200мл', calories: 80, protein: 0.3, fat: 0.1, carbs: 20 },
  { id: 194, name: 'Вода', category: 'drink', portion: '500мл', calories: 0, protein: 0, fat: 0, carbs: 0 },
  { id: 195, name: 'Вода газированная', category: 'drink', portion: '500мл', calories: 0, protein: 0, fat: 0, carbs: 0 },
  { id: 196, name: 'Вода минеральная', category: 'drink', portion: '500мл', calories: 0, protein: 0, fat: 0, carbs: 0 },
  { id: 197, name: 'Протеиновый коктейль', category: 'drink', portion: '300мл', calories: 150, protein: 25, fat: 2, carbs: 8 },
  { id: 198, name: 'Гейнер', category: 'drink', portion: '300мл', calories: 350, protein: 20, fat: 6, carbs: 55 },
  { id: 199, name: 'Коктейль молочный', category: 'drink', portion: '300мл', calories: 250, protein: 10, fat: 8, carbs: 35 },
  { id: 200, name: 'Смузи зелёный', category: 'drink', portion: '300мл', calories: 120, protein: 4, fat: 2, carbs: 24 },
  { id: 201, name: 'Энергетик', category: 'drink', portion: '250мл', calories: 110, protein: 0, fat: 0, carbs: 27 },
  { id: 202, name: 'Кола', category: 'drink', portion: '330мл', calories: 140, protein: 0, fat: 0, carbs: 35 },
  { id: 203, name: 'Пепси', category: 'drink', portion: '330мл', calories: 140, protein: 0, fat: 0, carbs: 35 },
  { id: 204, name: 'Фanta', category: 'drink', portion: '330мл', calories: 140, protein: 0, fat: 0, carbs: 35 },
  { id: 205, name: 'Sprite', category: 'drink', portion: '330мл', calories: 140, protein: 0, fat: 0, carbs: 35 },
];

export const workoutsDatabase = [
  { id: 1, name: 'Тренировка A (upper body)', type: 'strength', difficulty: 'intermediate', duration: 45 },
  { id: 2, name: 'Тренировка B (lower body)', type: 'strength', difficulty: 'intermediate', duration: 50 },
  { id: 3, name: 'Кардио HIIT', type: 'cardio', difficulty: 'advanced', duration: 30 },
  { id: 4, name: 'Утренняя растяжка', type: 'flexibility', difficulty: 'beginner', duration: 20 },
  { id: 5, name: 'Полная тренировка', type: 'mixed', difficulty: 'intermediate', duration: 60 },
  { id: 6, name: 'Тренировка для начинающих', type: 'strength', difficulty: 'beginner', duration: 35 },
  { id: 7, name: 'Беговая тренировка', type: 'cardio', difficulty: 'intermediate', duration: 40 },
  { id: 8, name: 'Йога для спины', type: 'flexibility', difficulty: 'beginner', duration: 45 }
];

export function searchFoods(query) {
  if (!query || query.length < 2) return foodDatabase.slice(0, 15);
  const lowerQuery = query.toLowerCase();
  return foodDatabase.filter(food => food.name.toLowerCase().includes(lowerQuery));
}

export function getFoodsByCategory(category) {
  return foodDatabase.filter(food => food.category === category);
}

export function getCategories() {
  return [...new Set(foodDatabase.map(food => food.category))];
}

export function formatFoodEntry(food, multiplier = 1) {
  return {
    name: food.name,
    portion: food.portion,
    calories: Math.round(food.calories * multiplier),
    protein: Math.round(food.protein * multiplier * 10) / 10,
    fat: Math.round(food.fat * multiplier * 10) / 10,
    carbs: Math.round(food.carbs * multiplier * 10) / 10,
    category: food.category,
    date: new Date().toISOString().split('T')[0]
  };
}

export default {
  foodDatabase,
  workoutsDatabase,
  searchFoods,
  getFoodsByCategory,
  getCategories,
  formatFoodEntry
};